spring.application.name= insta-auth
server.port= 9000
eureka.client.service-url.default-zone= http://localhost:8761/eureka

data.mongodb.database= instaclone_auth

spring.cloud.stream.kafka.binder.brokers= localhost:9092
spring.cloud.stream.kafka.binder.configuration.key.serializer= org.apache.kafka.common.serialization.StringSerializer

spring.cloud.stream.bindings.momentsUserChanged.destination= moments.user.changed
spring.cloud.stream.bindings.momentsUserChanged.contentType= application/json

security.basic.enable= false

security.jwt.uri= /auth/**
security.jwt.header= Authorization
security.jwt.prefix= Bearer
security.jwt.expiration= 86400
security.jwt.secret= JwtSecretKey


security.service.username= d245ef53-5ad5-4216-9c56-89fe0f8302a0
security.service.password= ef919ae4-b893-4969-b782-57978180ad33